import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css';
import ReactQueryProvider from "@/providers/react-query";
import Catalog from "./Catalog/page";
import HeaderMenu from "@/components/HeaderMenu/HeaderMenu";
import Footer from "@/components/Footer/Footer";
import Main from "@/components/Main/Main";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className}>{children}
      <ReactQueryProvider children={undefined}>
        {/* <HeaderMenu/> */}
        {/* <Main/> */}
        {/* <Footer/> */}
        </ReactQueryProvider>
        </body>
    </html>
  );
}

